name: cron Test at New repo

on:
  workflow_dispatch:

  push:

  # schedule:
  #   - cron: '0,30 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Schedule Test at New repo"