name: Schedule Test by New repo

on:
  workflow_dispatch:

  push:

  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Schedule Test by New repo"